<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
	<link type="text/css" href="<?=Class_Server::extUrl()?>/reset-backend.css" media="screen" rel="stylesheet">
	<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/jub.js"></script>
	
	<title><?=$this->pageTitle ?></title>
</head>

<body>
	<div class='body_main_frame'>
		<?php echo $this->layout()->content ?>
	</div>
</body>
</html>