<table class='data'>
</table>
<ul class='paginator'>
</ul>

<script>
	window.dataRowActions = {'edit':'编辑'};
</script>

<script type='text/template' id='data-row'>
<%_.each(data, function(type, key) {if(key != 'id') {%>
	<td>{{type}}</td>
<%}});%>

<td>
<%
_.each(window.dataRowActions, function(label, action) {
%>
	<a href='/admin/org/{{action}}/id/{{data.id}}'>{{label}}</a>
<%
});
%>
</td>
</script>
<script data-main="http://st.onlinefu.com/ext/model/main" src="http://st.onlinefu.com/ext/model/require-jquery.js"></script>